// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_supernova = "CgkIyd3Wzt0MEAIQDg"; // <GPGSID>
        public const string leaderboard_leaderboardnametest = "CgkIyd3Wzt0MEAIQAg"; // <GPGSID>
        public const string event_devisepremiumtest = "CgkIyd3Wzt0MEAIQAA"; // <GPGSID>
        public const string achievement_symbiosis = "CgkIyd3Wzt0MEAIQEA"; // <GPGSID>
        public const string achievement_extinction = "CgkIyd3Wzt0MEAIQDA"; // <GPGSID>
        public const string achievement_life_find_always_the_good_way = "CgkIyd3Wzt0MEAIQFg"; // <GPGSID>
        public const string achievement_hello_world = "CgkIyd3Wzt0MEAIQAQ"; // <GPGSID>
        public const string achievement_master = "CgkIyd3Wzt0MEAIQBA"; // <GPGSID>
        public const string achievement_god_bless_america = "CgkIyd3Wzt0MEAIQEw"; // <GPGSID>
        public const string achievement_little_step_for_man_big_for_humanity = "CgkIyd3Wzt0MEAIQFQ"; // <GPGSID>
        public const string achievement_let_it_burn = "CgkIyd3Wzt0MEAIQFA"; // <GPGSID>

}

